config/routes.rb
Rails.application.routes.draw do
  # get 'home/top'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # def "layouts/application" => "layouts#application"
  # end
  # Defines the root path route ("/")
  # root "articles#index"
  
  # User画面
  get "/" => "home#top"
  get "/class" => "home#class"
  get "/kids" => "home#kids"
  get "/general" => "home#general"
  get "/personal" => "home#personal"
  get "/trial" => "home#trial"
  get "/access" => "home#access"
  get "/counseling" => "home#counseling"
  get "/ocha_dailypost_show/:id" => "home#ocha_dailypost_show"

  # 管理者画面用
  get "admin/top" => "admin#top"

  get "daily_post/index" => "daily_post#index", as: 'daily_post_index' #一覧
  get "daily_post/new" => "daily_post#new", as: 'daily_post_new' #新規作成画面遷移
  post "daily_post/create" => "daily_post#create", as: 'daily_post_create' #新規保存
  get "daily_post/show/:id" => "daily_post#show", as: 'daily_post_show' #詳細画面遷移
  get "daily_post/edit/:id" => "daily_post#edit", as: 'daily_post_edit' #編集画面遷移
  get "daily_post/image_edit/:id" => "daily_post#image_edit", as: 'daily_post_image_edit' #編集画面遷移
  put "daily_post/:id" => "daily_post#update", as: 'daily_post_update' #編集更新
  delete "daily_post/:id" => "daily_post#delete", as: 'daily_post_delete' #投稿削除
  put "daily_post/image/:id" => "daily_post#image_delete", as: 'daily_post_image_delete' #サブ画像削除
  put "daily_post/is_open/:id" => "daily_post#is_open", as: 'daily_post_is_open' #サブ画像削除

  resources :contacts, only: %i[new create] do
    collection do
      post :confirm
      get :complete
    end
  end

  resources :reserves, only: %i[new create] do
    collection do
      post :confirm
      get :complete
    end
  end


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/contact.rb
class Contact < ApplicationRecord
    validates :name, presence: true
    validates :email, presence: true
    validates :telephone, presence: true, length: { maximum: 11 }
    validates :content_inquiry, presence: true

    validate :email_format
    validate :telephone_format

    private

    # メールアドレスの形式チェック
    def email_format
        return if /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i.match?(email)
        
        errors.add(:email, "の形式が正しくありません")
    end

    # 電話番号のフォーマット自動調整？？
    def telephone_format
        return if telephone.blank?

        self.telephone = telephone.tr('０-９', '0-9').delete('^0-9')
    end


end

app/models/daily_post.rb
class DailyPost < ApplicationRecord
  validates :title, presence: true
  validates :content, presence: true
  validates :img_main, presence: true

  has_one_attached :img_main
  has_many_attached :images_sub

end

app/models/reserve.rb
class Reserve < ApplicationRecord
    validates :name, presence: true
    validates :email, presence: true
    validates :telephone, presence: true, length: { maximum: 11 }
    validates :content_inquiry, presence: true
    validates :reserve_date1, presence: true

    validate :email_format
    validate :telephone_format

    private

    # メールアドレスの形式チェック
    def email_format
        return if /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i.match?(email)
        
        errors.add(:email, "の形式が正しくありません")
    end

    # 電話番号のフォーマット自動調整？？
    def telephone_format
        return if telephone.blank?

        self.telephone = telephone.tr('０-９', '0-9').delete('^0-9')
    end


end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def top
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
    def new
        @contact = Contact.new
    end

    def confirm
        @contact = Contact.new(contact_params)
        return render :new if @contact.invalid?
        @contact.valid?
    end

    def create
        @contact = Contact.new(contact_params)
        return render :new if params[:button] == "back"
        if @contact.save
            ContactMailer.mail_to_user(@contact.id).deliver_now
            ContactMailer.mail_to_staff(@contact.id).deliver_now
            return redirect_to complete_contacts_url
        end

        render :confirm
    end

    private

    def contact_params
        params.require(:contact).permit(:name, :email, :telephone, :content_inquiry)
    end

end

app/controllers/daily_post_controller.rb
class DailyPostController < ApplicationController
  def index
    @daily_posts = DailyPost.all
    @is_open_count = @daily_posts.where(is_open: true).count
    @daily_posts = DailyPost.order(created_at: :desc).page(params[:page]).per(5)
  end
  
  def new
    @daily_post = DailyPost.new
  end

  def create
    @daily_Post = DailyPost.new(daily_post_params)
    if @daily_Post.save
      redirect_to action: :index
    else
      flash[:alert] = "投稿に失敗しました"
      render :new
    end
  end

  def show
    @daily_post = DailyPost.find(params[:id])
  end

  def edit
    @daily_post = DailyPost.find(params[:id])
  end

  def image_edit
    @daily_post = DailyPost.find(params[:id])
  end

  def image_delete
    @daily_post = DailyPost.find(params[:id])
    @images_sub_id = []
    @image_sub_hash = {}
    if daily_post_imagesSub[:images_sub] != nil
      @daily_post.images_sub.each do |image|
        if daily_post_imagesSub.has_value?("")
          @daily_post.images_sub.purge
          flash[:success] = "削除しました"
          redirect_to action: :show
        elsif daily_post_imagesSub[:images_sub].include?(image.signed_id)
          next
        else
          @images_sub_id.push(image.signed_id)
        end
      end
      @image_sub_hash = {"images_sub" => @images_sub_id}
      @daily_post.update(@image_sub_hash)
      flash[:success] = "削除しました"
      redirect_to action: :show
    else
      flash[:alert] = "削除に失敗しました"
      render :image_edit
    end
  end

  def update
    @daily_post = DailyPost.find(params[:id])
    if @daily_post.update(daily_post_params)
      flash[:success] = "編集しました"
      redirect_to action: :show
    else
      flash[:alert] = "更新に失敗しました"
      render :edit
    end
  end

  def is_open
    @daily_post = DailyPost.find(params[:id])
    # "非表示にしました"
    if @daily_post.is_open
      @daily_post.update(is_open: false)
    # "表示にしました"
    else
      @daily_post.update(is_open: true)
    end
    redirect_to action: :index
  end
  
  private
  def daily_post_params
    params.require(:daily_post).permit(:title, :content, :img_main, images_sub: [])
  end

  def daily_post_imagesSub
    params.permit(images_sub: [])
  end
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
    @daily_posts_home = DailyPost.where(is_open: true).order(created_at: :desc).limit(3)
  end

  def ocha_dailypost_show
    @daily_post_home = DailyPost.find(params[:id])
  end
end

app/controllers/reserves_controller.rb
class ReservesController < ApplicationController
    def new
        @reserve = Reserve.new
    end

    def confirm
        @reserve = Reserve.new(reserve_params)
        return render :new if @reserve.invalid?
        @reserve.valid?
    end

    def create
        @reserve = Reserve.new(reserve_params)
        return render :new if params[:button] == "back"
        if @reserve.save
            ReserveMailer.mail_to_user(@reserve.id).deliver_now
            ReserveMailer.mail_to_staff(@reserve.id).deliver_now
            return redirect_to complete_reserves_url
        end

        render :confirm
    end

    private

    def reserve_params
        params.require(:reserve).permit(:name, :email, :telephone, :content_inquiry, :reserve_date1, :reserve_date2, :reserve_date3)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/top.html.erb
<%= render partial: 'layouts/admin_header' %>
<ul class="center-block" style="width: 100%; height: 40vh; margin-top: 20vh;">
  <li class="h3"><a href="/daily_post/index">日記一覧</a></li>
  <li class="h3"><a href="/daily_post/new">日記新規作成</a></li>
  <li class="h3"><a>体験予約一覧（追加予定）</a></li>
</ul>

app/views/contacts/complete.html.erb
<div class="text-center height_auto mg_10px mb_5">
    <div class="contact mt_25vh_sp">
        <h3>送信完了</h3>
    </div>

    <div class="text_center pd_y_10 vh_25_sp vh_35">
        <p class="line_height_sm line_height_sm_sp">
            お問い合わせありがとうございます。<br>
            後ほど折り返しご連絡差し上げます。<br>
            いましばらくお待ちください。
        </p>
    </div>

    <div class="flex flex_center">
        <div class="complete_btn mg_20px">
            <a href="/">ホームに戻る</a>
        </div>
    </div>
</div>

<script>
    $(function() {
        $('header').show();
    });
</script>

app/views/contacts/confirm.html.erb
<div class="text-center height_auto mg_10px mb_5">
    <div class="contact mt_20vh_sp">
        <h3>お問い合わせ内容の確認</h3>
    </div>

    <div class="">
        <p class="mb_1_sp">以下の内容でよろしいでしょうか？</p>
        <div class="pd_5 vw_50 mg_0 pc_display">
            <table class="table mg_auto_contact table_color" style="width: 50vw !important;">
                <tr>
                    <th style="border-top: none; border-bottom: none;"></th>
                    <th style="border-top: none; border-bottom: none;"></th>
                </tr>
                <tr>
                    <td style="border-top: none;"><%= t("activerecord.attributes.contact.name")%></td>
                    <td style="border-top: none;"><%= @contact.name %></td>
                </tr>
                <tr>
                    <td><%= t("activerecord.attributes.contact.email")%></td>
                    <td><%= @contact.email %></td>
                </tr>
                <tr>
                    <td><%= t("activerecord.attributes.contact.telephone")%></td>
                    <td><%= @contact.telephone %></td>
                </tr>
                <tr>
                    <td><%= t("activerecord.attributes.contact.content_inquiry")%></td>
                    <td><%= @contact.content_inquiry %></td>
                </tr>
            </table>
        </div>
        <div class="sp_display text_left">
            <p class="pl_10vw_sp mt_5_sp">◎<%= t("activerecord.attributes.contact.name")%></p>
            <p class="pl_10vw_sp"><%= @contact.name %></p>
            <p class="pl_10vw_sp">◎<%= t("activerecord.attributes.contact.email")%></p>
            <p class="pl_10vw_sp"><%= @contact.email %></p>
            <p class="pl_10vw_sp">◎<%= t("activerecord.attributes.contact.telephone")%></p>
            <p class="pl_10vw_sp"><%= @contact.telephone %></p>
            <p class="pl_10vw_sp">◎<%= t("activerecord.attributes.contact.content_inquiry")%></p>
            <p class="pl_10vw_sp mb_4_sp"><%= @contact.content_inquiry %></p>
        </div>
    </div>
    <div class="flex flex_center">
        <br>
        <%= form_for @contact, url: contacts_path do |f| %>
            <%= f.hidden_field :name %>
            <%= f.hidden_field :email %>
            <%= f.hidden_field :telephone %>
            <%= f.hidden_field :content_inquiry %>
            <%= f.button "OK", class:"complete_btn mg_20px" %>
        <% end %><br>
        <%= form_for @contact, url: contacts_path do |f| %>
            <%= f.hidden_field :name %>
            <%= f.hidden_field :email %>
            <%= f.hidden_field :telephone %>
            <%= f.hidden_field :content_inquiry %>
            <%= f.button "戻る", value: "back" , class:"complete_btn mg_20px" %>
        <% end %>
    </div>
</div>

<script>
    $(function() {
        $('header').show();
    });
</script>

app/views/contacts/new.html.erb
<div class="text-center height_auto mg_10px">
    <div class="mb_5 mt_20vh_sp">
        <h1 class="mb_3">【お問い合わせ】</h1>
        <p class="line_height_sm bgc_gray pd_1">
            お名前、ご連絡先、お問い合わせ内容<br class="sp">をご入力ください。<br>
            茶道の経験はないが、何か新しいことを始めたい<br>
            お稽古内容の詳細が知りたい<br>
            子供の習い事で少し気になった 等々<br>
            お気軽にどうぞお問い合わせください♪
        </p>
    </div>
    <%= form_for @contact, url: confirm_contacts_path do |f| %>
        <div class="mb_5">
            <%= f.label :name, class:"vw_30 text_left ml_2 vw_70_sp" %><br>
            <%= f.text_field :name, class:"vw_30 vw_70_sp" %>
            <% @contact.errors.full_messages_for(:name).each do |message| %>
                <div class="error">*<%= message %></div>
            <% end %>
        </div>
        <div class="mb_5">
            <%= f.label :email, class:"vw_30 text_left ml_2 vw_70_sp" %><br>
            <%= f.text_field :email, class:"vw_30 vw_70_sp" %>
            <% @contact.errors.full_messages_for(:email).each do |message| %>
                <div class="error">*<%= message %></div>
            <% end %>
        </div>
            <div class="mb_5">
            <%= f.label :telephone, class:"vw_30 text_left ml_2 vw_70_sp" %><br>
            <%= f.text_field :telephone, class:"vw_30 vw_70_sp" %>
            <% @contact.errors.full_messages_for(:telephone).each do |message| %>
                <div class="error">*<%= message %></div>
            <% end %>
        </div>
        <div class="mb_5">
            <%= f.label :content_inquiry, class:"vw_50 text_left ml_2 vw_70_sp" %><br>
            <%= f.text_area :content_inquiry, class:"vh_15 vw_50 vw_70_sp" %>
            <% @contact.errors.full_messages_for(:content_inquiry).each do |message| %>
                <div class="error">*<%= message %></div>
            <% end %>
        </div>
        <%= f.button "確認画面へ", class:"confrim_btn mb_5 pd_btn" %>
    <% end %>
</div>

<script>
    $(function() {
        $('header').show();
    });
</script>

app/views/daily_post/edit.html.erb
<%= render partial: 'layouts/admin_header' %>

<div class="center-block text-center" style="height: auto; width: 90vw; ">
  <%= form_for @daily_post, url: daily_post_update_path, method: :put do |form| %>
    <p class="mt_3">タイトル</p>
    <%= form.text_field :title, class: "mt_3", value: @daily_post.title, required: true %><br>
    <p class="mt_3">内容</p>
    <%= form.text_area :content, class: "vw_50 vh_35 mt_3", value: @daily_post.content, required: true %><br>
    <p class="mt_3">メイン画像（１枚のみ）</p>
    <%= image_tag @daily_post.img_main, class: "vw_50 vh_35 mt_3", required: true %>
    <div class="inline_block"><%= form.file_field :img_main, value: @daily_post.img_main.signed_id %></div><br>
    <p class="mt_3">サブ画像（複数可能）* 1~3枚推奨<br class="sp">（正方形で表示。２列に並びます。）</p>

    <% @daily_post.images_sub.each do |image| %>
      <%= form.hidden_field :images_sub, multiple: true, value: image.signed_id %>
      <%= image_tag image, size:"100x100" %> <br>
    <% end %>

    <%= form.file_field :images_sub, multiple: true, accept: "image/*" %>
    <%= submit_tag("保存", class: "mt_3 mb_5") %>
  <% end %>
</div>

app/views/daily_post/image_edit.html.erb
<%= render partial: 'layouts/admin_header' %>

<div class="center-block text-center" style="height: auto; width: 90vw; ">
  <p>現在登録されている画像（削除する画像をチェックしてください）</p>
  <%= form_for @daily_post, url: daily_post_image_delete_path, method: :put do |form| %>
    <input type="checkbox" id="all_delete_images_sub" name="images_sub[]" value="">
    <p>全件削除</p>
    <% @daily_post.images_sub.each do |image| %>
      <input type="checkbox" id="images_sub" class="checks" name="images_sub[]" value="<%= image.signed_id %>">
      <%= image_tag image, size:"100x100" %> <br>
    <% end %>
    <input type="submit" value="削除">
  <% end %>
</div>

<script>
  const checkall = document.getElementById("all_delete_images_sub");
  const checks = document.querySelectorAll(".checks");

  checkall.addEventListener('click', () => {
    for (val of checks) {
      checkall.checked == true ? val.checked = true : val.checked = false;
    }
  });
</script>

app/views/daily_post/index.html.erb
<%= render partial: 'layouts/admin_header' %>
<div class="center-block text-center" style="height: auto; width: 100%; ">
  <div>
  日記一覧
  </div>
  <p>TOP画面表示数は<%= @is_open_count %>です</p>
  <div>
    <table class="post_table">
      <thead>
        <tr>
          <th class="align-middle text-center" scope="col">日付</th>
          <th class="align-middle text-center" scope="col">メイン画像</th>
          <th class="align-middle text-center" scope="col" style= "width:25%;">タイトル</th>
          <%# <th class="align-middle text-center" scope="col">内容</th> %>
          <th class="align-middle text-center" scope="col">詳細<br>ボタン</th>
          <th class="align-middle text-center" scope="col">top<br>画面<br>表示</th>
        </tr>
      </thead>
      <tbody class="table-group-divider">
        <% @daily_posts.each do |daily_post| %>
          <tr>
            <td class="align-middle"><%= daily_post.created_at.strftime("%Y") %><br><%= daily_post.created_at.strftime("%m/%d") %></td>
            <td class="align-middle" style= "width:25%; height:200px;">
              <% if daily_post.img_main.attached? %>
                <%= image_tag daily_post.img_main, style: "width:90%; height:90%;" %>
              <% else %>
                <%= ix_image_tag('no-image.png', tag_options: { style: "width:90%; height:90%;" }) %>
              <% end %>
            </td>
            </td>
            <td class="align-middle"><%= daily_post.title.truncate(7, omission: '~~') %></td>
            <%# <td class="align-middle"><%= daily_post.content.truncate(10, omission: '~~') %></td>
            <td class="align-middle"><%= link_to "詳細", daily_post_show_path(daily_post.id) %></td>
            <td class="align-middle">
              <% if daily_post.is_open %>
                <%= form_for daily_post, url: daily_post_is_open_path(daily_post.id), method: :put do |form| %>
                <input type="hidden" id="is_open" value="<%= daily_post.is_open %>">
                <%= submit_tag("非表示", class: "mt_3 mb_5") %>
                <% end %>
              <% else %>
                <%= form_for daily_post, url: daily_post_is_open_path(daily_post.id), method: :put do |form| %>
                <input type="hidden" id="is_open" value="<% daily_post.is_open %>">
                <%= submit_tag("表示", class: "mt_3 mb_5", id: "save_button") %>
                <% end %>
              <% end %>
              </td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <div class="pagination large">
      <%= paginate @daily_posts %>
    </div>
  </div>
</div>

<script>
var is_open_count = <%= @is_open_count %>;
document.getElementById("save_button").addEventListener("click", function() {
  if (is_open_count === 3) {
    alert("表示出来る投稿は最大３つまでです");
    event.preventDefault();
  }
});
</script>

app/views/daily_post/new.html.erb
<%= render partial: 'layouts/admin_header' %>
<div class="center-block text-center" style="height: auto; width: 90vw; ">
  <%= form_for @daily_post, url: daily_post_create_path, method: :post do |form| %>
    <p class="mt_3">タイトル</p>
    <%= form.text_field :title, class: "mt_3", required: true %><br>

    <p class="mt_3">内容</p>
    <%= form.text_area :content, class: "vw_50 vh_35 mt_3", required: true %><br>

    <p class="mt_3">メイン画像（１枚のみ）</p>
    <div class="inline_block"><%= form.file_field :img_main, required: true %></div><br>

    <p class="mt_3">サブ画像（複数可能）* 1~3枚推奨<br class="sp">（最大6枚可能。画像が少し縦長になります。）</p>
    <div class="inline_block"><%= form.file_field :images_sub, multiple: 6, accept: "image/*"%></div><br>
    <%= submit_tag("保存", class: "mt_3 mb_5", id: "save_button") %>
  <% end %>
</div>

app/views/daily_post/show.html.erb
<%= render partial: 'layouts/admin_header' %>
<%= button_to '編集する', daily_post_edit_path(@daily_post.id), method: :get, class: 'edit-button' %>
<%= button_to '画像を削除する', daily_post_image_edit_path(@daily_post.id), method: :get, class: 'edit-button' %>
<%= link_to '戻る', 'javascript:history.back ()', class: 'edit-button' %>


<div class="center-block text-center height_auto daily_post_width daily_post_width_pc" style="height: auto;">
  <% if !@daily_post.nil? %>
    <h1><%= @daily_post.title %></h1>
    <%# メイン画像 %>
    <div class="align-middle inline_block mt_3 mb_5 img_center" style= "width: 100%; height:40%;">
      <% if @daily_post.img_main.attached? %>
        <div><%= image_tag @daily_post.img_main , class: "daily_post_mainimg" %></div>
      <% else %>
        <div style ="width:90%; height:90%;"><%= ix_image_tag('no-image.png') %></div>
      <% end %>
    </div>
    <%# 内容テキスト %>
    <div class ="mt_3 line_height_md line_height_sm_sp w_100sp pd_2 text_left" style= "margin: auto;">
      <%= simple_format(@daily_post.content) %>
    </div>
    <%# サブ画像 6枚まで %>
    <div class="mt_3 mb_10 daily_post_flex" style= "height: auto; width: 100%;">
      <% if @daily_post.images_sub.attached? %>
        <% @daily_post.images_sub.each do |image_sub| %>
          <div class= "daily_post_subimg"><%= image_tag image_sub, style: "width: 100%; height: 100%;" %></div>
        <% end %>
      <% end %>
    </div>
  <% else %>
    <h2>レコードが見つかりません</h2>
  <% end %>
</div>

app/views/home/appearance.html.erb
<h1>お稽古の様子</h1>
<div class="appearance-img">
    <img src="appearance1.jpg">
    <img src="appearance2.jpg">
</div>
<div class="appearance">
<p>
初めての方は、客の所作や割稽古から始めます。<br>
続いて盆略点前・薄茶点前他...と進度に合わせて稽古を進めます。<br>
また、希望される方には許状申請も行います。<br>
各々の茶道への思いに合わせ稽古を進めてまいります。<br>
</p>
</div>

app/views/home/trial.html.erb
<div class="text-center">
    <div class="flex flex_column_sp">
        <div class="text-center display_none mt_3_sp" id="triallImg">
            <%= ix_image_tag("experience.jpg", tag_options: { class: "bg_img" })%>
        </div>
        <div class="">
            <h3 class="line_height_sm mb_3 pd_l_10 text_left letter_spacing_md text_center_sp pd_sm_sp">体験教室</h3>
            <p class="vw_50 pd_l_10 text_left line_height_md text_center_sp pd_sm_sp line_height_sm_sp">
                予約フォームよりご予約下さい。<br>
                お電話やメールでも受け付けております。<br>
                詳細等、お気軽にお問合せください。<br>
                個々のご事情に合わせて対応させていただきます。<br>
            </p>
            <div class="trial_btn">
                <%= link_to "体験予約はこちらから", new_reserf_path %>
            </div>
            <div class="trial_btn">
                <%= link_to "お問い合わせはこちらから", new_contact_path %>
            </div>
        </div>
    </div>
    <div class="mb_5">
        <h3 class="letter_spacing_md mt_10">～体験稽古/料金～</h3>
            <div class="pd_5 pd_0_sp">
                <table class="table mg_0">
                    <tr>
                    <th>1回　(約90分)</th>
                    </tr>
                    <tr>
                    <td>2000円 / 1人</td>
                    </tr>
                </table>
            </div>
    </div>
</div>

<script>
    $(window).on('load', function () {
        setTimeout(function () {
            $('#triallImg').fadeIn(2000);
        },);
    });

    $(function() {
        $('header').show();
    });

</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OchaApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "top", "admin", media: 'all', "data-turbo-track": "reload" %>

  <%# bootstrap jquery %>
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>


    <!-- jquery -->
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <%# google font %>
    <link href="https://fonts.googleapis.com/css2?family=Klee+One&family=Noto+Serif+JP:wght@200&display=swap" rel="stylesheet">
    <%# googleアナリティクス認識用スクリプト %>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());
      gtag('config', 'G-78GYS50PFF');
    </script>
  </head>
  <body>
    <header>
      <div class="flex between w_100">
        <a class="link letter_spacing_sm" href="/">茶道教室<br>SAKURA　CLUB</a>
        <div>
          <table class="pc_display">
            <tr>
              <td><a class="link ml_2 letter_spacing_sm" href="/counseling">カウンセリング</a></td>
              <td><a class="link ml_2 letter_spacing_sm" href="/class">クラス・お月謝</a></td>
              <td><a class="link ml_2 letter_spacing_sm" href="/trial">体験教室</a></td>
              <td><a class="link ml_2 letter_spacing_sm" href="/access">アクセス</a></td>
              <td><%= link_to "お問い合わせ", new_contact_path, class: "link ml_2 letter_spacing_sm" %></td>
            </tr>
          </table>
          <%# <div class="mr_2"> %>
            <nav class="sp_display">
              <input id="menu__toggle" type="checkbox" />
              <label class="menu__btn" for="menu__toggle">
                <span></span>
              </label>
              <ul class="menu__box">
                <li><a class="menu__item" href="/"><span class="red">Home</span></a></li>
                <li><a class="menu__item" href="/counseling">カウンセリング</a></li>
                <li><a class="menu__item" href="/class">クラス・お月謝</a></li>
                <li><a class="menu__item" href="/trial">体験教室</a></li>
                <li><a class="menu__item" href="/access">アクセス</a></li>
                <li><%= link_to "お問い合わせ", new_contact_path, class: "menu__item" %></li>
              </ul>
            </nav>
          <%# </div> %>
        </div>
      </div>
    </header>
    <%= yield %>
    <footer>
      <p class="absolute bottom_0 left_0 letter_spacing_sm line_height_sm mg_2 top_0_sp line_height_0_sp">茶道教室<br>SAKURA　CLUB</p>
      <div class="absolute bottom_0 right_0 flex flex_column mg_1 line_height_0_sp text_right">
        <a class="link" href="mailto:sakura.club.info@gmail.com">メールアドレス：sakura.club.info@gmail.com</a>
        <a class="link" href="tel:080-1099-5052">電話番号：080-1099-5052</a>
        <a class="link" href="https://www.instagram.com/chadou_sakura/">instagramはこちら</a>
        <%= link_to "【　お問い合わせはこちらから　】", new_contact_path, class: "link" %>
      </div>
    </footer>
  <body>
</html>